vcap:
  application:
    name: '@project.name@'
spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: "off"
  cloud:
    bus:
      enabled: false
    config:
      enabled: false
eureka:
  client:
    enabled: false
info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'